language: perl
sudo: required
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
addons:
   postgresql: "9.6"
env:
  - COVERAGE=1 RELEASE_TESTING=1 DB_TESTING=1
before_install:
   - t/helpers/travis-setup.sh
   # temporary
   - sudo cpanm --installdeps --notest https://cpan.metacpan.org/authors/id/E/EI/EINHVERFR/PGObject-Util-PGConfig-v0.01.02.tar.gz
   - sudo cpanm --installdeps --notest https://cpan.metacpan.org/authors/id/E/EI/EINHVERFR/PGObject-Util-Replication-Slot-v0.01.02.tar.gz
   - eval $(curl https://travis-perl.github.io/init) --auto

